project:
  type: website

website:
  title: "south-florida-salinity"
  navbar:
    left:
      - href: index.qmd
        text: Home

      - href: ndbc_salinity_map.qmd
        text: NDBC Salinity Map

      - href: ndbc_salinity_gauges.qmd
        text: Salinity Gauges

      - href: ndbc_temperature_map.qmd
        text: NDBC Temperature Map

      - href: mur_sst_anomaly_florida_keys.qmd
        text: MUR SST Anomaly
        
#      - text: Downstream Flows
#        menu:
#        - riverflows/riverflowSouth.qmd
#        - riverflows/riverflowEast.qmd
#        - riverflows/riverflowWest.qmd
#        - riverflows/riverflowSoutheast.qmd
#        - riverflows/riverflowSouthwest.qmd
        
      - href: https://github.com/usf-imars/south-florida-salinity
        text: Source Code on GitHub

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    code-fold: true
    message: false
    warning: false
